In [1]:
import numpy as np
list_ = [ "1","2","3","4","5" ]
array_list = np.array(object = list_)
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [3]:
#Q1
"""
In Python, list and array are two different data types. 
However, it seems you're referring to two variables list_ and array_list.
Without further context, it's not clear what array_list refers to.
Assuming array_list is a variable containing an array, typically
represented using the array module in Python, 
it would indeed have a different data type from a regular list.
"""
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [4]:
#Q2
print("Data type of elements in list_:")
for element in list_:
    print(type(element))

# Print data type of each element in array_list
print("\nData type of elements in array_list:")
for element in array_list:
    print(type(element))

Data type of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [5]:
#Q3
array_list = np.array(object = list_, dtype = int)
array_list

array([1, 2, 3, 4, 5])

In [6]:
print("Data type of elements in list_:")
for element in list_:
    print(type(element))

# Print data type of each element in array_list
print("\nData type of elements in array_list:")
for element in array_list:
    print(type(element))

Data type of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [7]:
#Q4
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [9]:
#Q4.i
print(num_array.shape)
#Q4.ii
print(num_array.size)

(2, 3)
6


In [18]:
#Q5
a=np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
#Q6
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])